import Sidebar from '@/components/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'
import SessionProvider from '@/components/SessionProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import Login from '@/components/Login'
import ToastWrapper from '@/components/ToastWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions)

  return (
    <html lang='en'>
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className='flex'>
              {/* Sidebar */}
              <Sidebar />
              {/* Client Provider */}
              <div className='flex-1 bg-GRAY_1'>{children}</div>
              <ToastWrapper />
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
